### PR TITLE
Add zsh completion

### PR DESCRIPTION
**Pull request by vladimyr**
Hi @majjoha 👋 

Thanks for building this neat little utility.
I've added zsh completion to spare few keystrokes and improve command discoverability 🎉

### CODE REVIEW

**Comment by majjoha** [comment]
Hi @vladimyr,

You're welcome, and thank you for your pull request. It definitely looks like a useful addition. It might be worth adding completion for Bash in the future too.

My experience with zsh completion is fairly limited but I'd say it looks good. Where would I need to put the script in macOS to test it? Also, would you mind replacing the text in the `commands` variable so it is consistent with the information in `voxctl help`? I think it just needs to look like this instead:

```
'start:Starts VOX'
'quit:Quits VOX'
'play:Begins playback'
'pause:Pauses playback'
'togglePlay:Toggles playback between playing and paused ''
'next:Skips to the next track in the playlist'
'previous:Skips to the previous track in the playlist'
'shuffle:Toggles shuffle on or off'
'playUrl URL:Plays the specified URL'
'addUrl URL:Adds the specified URL to the playlist'
'rewindForward:Rewinds the current track forward'
'rewindForwardFast:Rewinds the current track forward fast'
'rewindBackward:Rewinds the current track backward'
'rewindBackwardFast:Rewinds the current track backward fast'
'increaseVolume:Increases the volume'
'decreaseVolume:Decreases the volume'
'togglePlaylist:Shows/hides the playlist'
'info:Displays information about the current track in JSON'
'isRunning:Prints true if VOX is open, otherwise false'
'help:Prints this information'
```

Thank you once again!

**Comment by vladimyr** [comment]
> It might be worth adding completion for Bash in the future too.

I'm learning how to do that. Being primarily zsh user I didn't actually have a need to write one 🙃 

> Where would I need to put the script in macOS to test it?

The canonical place would be `/usr/local/share/zsh/site-functions/` but you can simply source it for testing purposes.

> Also, would you mind replacing the text in the `commands` variable so it is consistent with the information in `voxctl help`?

Sure, I've changed it to match what I'm seeing elsewhere but keep in mind that `help` needs to be altered because there is no _this information_ in completion context. A possible alternative would be: `help:Prints help`, what do you think?

**Comment by majjoha** [comment]
> I'm learning how to do that. Being primarily zsh user I didn't actually have a need to write one 🙃

I am also a zsh user so perhaps it might be worth simply adding an issue and see if somebody else would be up for adding it.

> The canonical place would be `/usr/local/share/zsh/site-functions/` but you can simply source it for testing purposes.

Perfect. It seems to work great on my end. :-)

> Sure, I've changed it to match what I'm seeing elsewhere but keep in mind that `help` needs to be altered because there is no _this information_ in completion context. A possible alternative would be: `help:Prints help`, what do you think?

Good point! `help:Prints help` sounds good to me.

**Comment by vladimyr** [comment]
Command descriptions updated ✅

**Comment by majjoha** [comment]
Thank you!

**Comment by majjoha** [comment]
@vladimyr: I've updated the [Homebrew formula](https://github.com/majjoha/homebrew-tap/blob/master/Formula/voxctl.rb) so it now points to the latest version. The zsh completion script seems to be added correctly to `/usr/local/share/zsh/site-functions` but I am not experiencing any tab completion for `voxctl`. Does it work on your machine with the new formula? It may simply be an issue with my local zsh configuration.

**Comment by vladimyr** [comment]
@majjoha Issue you are experiencing is caused by me not respecting `compinit` [conventions](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#:~:text=When%20compinit%20is%20run%2C%20it%20searches,%5B%20%2DN%20name%20...%20%5D%20%5D). Long story short I had to put following in the first line:
```zsh
#compdef voxctl
```
PR is on the way 🛫

**Comment by majjoha** [comment]
Thank you for your great work!

**Pull request merged**
